### ISSUE TITLE
Wrong subtype for a PointSet element

### ISSUE THREAD

**Issue by rppioneer** [ericbdaniels/oomf#3]
Hi,

It is not possible to read an OMF file using the oomf package having a PointSet element of subtype "collar". As per OMF documentation, PointSet subtype could be one of the following string: "point", "collar" or "blasthole". Following is the link as reference.

[https://omf.readthedocs.io/en/stable/content/pointset.html#:~:text=subtype%20(StringChoice)%3A%20Category%20of%20PointSet%2C%20any%20of%20%E2%80%9Cpoint%E2%80%9D%2C%20%E2%80%9Ccollar%E2%80%9D%2C%20%E2%80%9Cblasthole%E2%80%9D%2C%20Default%3A%20point](https://omf.readthedocs.io/en/stable/content/pointset.html#:~:text=subtype%20(StringChoice)%3A%20Category%20of%20PointSet%2C%20any%20of%20%E2%80%9Cpoint%E2%80%9D%2C%20%E2%80%9Ccollar%E2%80%9D%2C%20%E2%80%9Cblasthole%E2%80%9D%2C%20Default%3A%20point)

But what I found after digging in the code is that it is set to "color" instead of "collar". I don't know where 'color' is coming from but this seems to be wrong.

[https://github.com/ericbdaniels/oomf/blob/master/oomf/elements.py#:~:text=%22point%22%3A%20PointSet%2C-,%22color%22%3A%20PointSet,-%2C](https://github.com/ericbdaniels/oomf/blob/master/oomf/elements.py#:~:text=%22point%22%3A%20PointSet%2C-,%22color%22%3A%20PointSet,-%2C)

Thanks.

**Comment by ericbdaniels** [comment]
Likely a typo, I'll take a look.

thanks for bringing this to my attention.
